name: Update Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run update test
        env:
          RV_TOKEN: ${{ secrets.RV_TOKEN }}
        run: |
          python scripts/update.py
